### ISSUE TITLE
import wiringpi 出错，提示No module named '_wiringpi'

### ISSUE THREAD

**Issue by czm2333** [orangepi-xunlong/wiringOP-Python#23]

**Comment by YingzhiLin** [comment]
我也遇到了同样的问题，您是如何解决的呢？

```
import wiringpi
Traceback (most recent call last):
File "", line 1, in
File "/usr/src/wiringOP-Python/wiringpi.py", line 15, in
import _wiringpi
ImportError: /usr/local/lib/python3.10/dist-packages/wiringpi-2.60.1-py3.10-linux-aarch64.egg/_wiringpi.cpython-310-aarch64-linux-gnu.so: undefined symbol: sunxi_pwm_set_clk
```

-------------------------

后记。看到了 https://github.com/orangepi-xunlong/wiringOP-Python/issues/25 ，问题解决了，非常感谢。

**Comment by YingzhiLin** [comment]
import wiringpi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/src/wiringOP-Python/wiringpi.py", line 15, in <module>
    import _wiringpi
ImportError: /usr/local/lib/python3.10/dist-packages/wiringpi-2.60.1-py3.10-linux-aarch64.egg/_wiringpi.cpython-310-aarch64-linux-gnu.so: undefined symbol: sunxi_pwm_set_clk
